<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <DalamudApiLevel>15</DalamudApiLevel>
    <Version>0.1.7</Version>
    <Description>Import EorzeaCollection glams and apply via Glamourer.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
		<DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="AngleSharp" Version="1.*" /> -->
    <!-- Optional: if you want explicit zips; otherwise omit and use SDK pack -->
    <!-- <PackageReference Include="DalamudPackager" Version="15.*" PrivateAssets="all" /> -->
  </ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Glamourer.Api\Glamourer.Api.csproj" />

  <Reference Include="Dalamud">
    <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Dalamud.Common">
    <HintPath>$(DalamudLibPath)Dalamud.Common.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Dalamud.Bindings.ImGui">
    <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
    <Private>false</Private>
  </Reference>

  <Reference Include="Lumina">
    <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Lumina.Excel">
    <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
    <Private>false</Private>
  </Reference>

  <!-- Optional -->
  <Reference Include="ImGuiScene">
    <HintPath>C:\Users\rossj\AppData\Roaming\XIVLauncher\addon\Hooks\dev\ImGuiScene.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="FFXIVClientStructs">
    <HintPath>C:\Users\rossj\AppData\Roaming\XIVLauncher\addon\Hooks\dev\FFXIVClientStructs.dll</HintPath>
    <Private>false</Private>
  </Reference>
</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\ec-piece-map.json" />
    <Content Include="Data\ec-piece-map.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
