name: Release (Plogon)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # you have Glamourer.Api as a submodule

      - name: Setup .NET (Plogon uses .NET 8)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Prepare Plogon workspace
        run: |
          set -e
          # Plogon expects all three channels to exist
          mkdir -p manifests/stable/EorzeaLink
          mkdir -p manifests/testing
          mkdir -p manifests/staging
          mkdir -p output work artifacts

          # minimal manifest in stable
          cat > manifests/stable/EorzeaLink/manifest.toml <<'EOF'
          [plugin]
          repository = "https://github.com/FuzzyCore/EorzeaLink.git"
          commit = "${{ github.sha }}"
          owners = [ "FuzzyCore" ]
          changelog = '''
          Automated build.
          '''
          EOF

          # optional icon
          if [ -f EorzeaLink/icon.png ]; then
            cp EorzeaLink/icon.png manifests/stable/EorzeaLink/icon.png
          fi

          # keep files so empty dirs persist in artifacts/logs if needed
          touch manifests/testing/.keep manifests/staging/.keep

      - name: Clone Plogon
        run: git clone https://github.com/goatcorp/Plogon.git

      - name: Build with Plogon
        working-directory: Plogon/Plogon
        run: |
          dotnet run -- \
            --manifest-folder="../../manifests" \
            --output-folder="../../output" \
            --work-folder="../../work" \
            --static-folder="static" \
            --artifact-folder="../../artifacts" \
            --mode=Development --build-all

      # Plogon drops built zips under artifacts/<PluginName>/
      - name: Show artifacts
        run: find artifacts -maxdepth 2 -type f -iname "*.zip" -print

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/**/*.zip
          generate_release_notes: true